import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { copyFileSync, mkdirSync } from 'node:fs';

// Patch process.release.name → "browser" so @huggingface/transformers treats
// Electron renderer as a browser env (IS_NODE_ENV = false) and picks
// onnxruntime-web (WASM) instead of onnxruntime-node (native C++ addon).
// Must be a banner (not inject) so esbuild never tree-shakes it away.
const ortEnvPatch = `(function(){if(typeof process!=="undefined"&&process.release&&process.release.name==="node"){try{Object.defineProperty(process,"release",{value:Object.assign({},process.release,{name:"browser"}),writable:true,configurable:true});}catch(_){}}})();`;

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
${ortEnvPatch}
`;

const prod = (process.argv[2] === "production");

// In dev mode, output directly to the local test vault for hot-reload.
// In production (CI), output to ./dist so the release workflow can pick up artifacts.
const outdir = prod
	? "./dist"
	: "C:\\Users\\matt\\Documents\\programming\\obsidian_test_vault\\.obsidian\\plugins\\phonolite";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
		...builtinModules.map(m => `node:${m}`)],
	define: {
		__DEV__: prod ? "false" : "true",
	},
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: `${outdir}/main.js`,
	minify: prod,
});

// Copy static assets needed for both dev and production releases
mkdirSync(outdir, { recursive: true });
copyFileSync("manifest.json", `${outdir}/manifest.json`);
copyFileSync("styles.css", `${outdir}/styles.css`);

if (!prod) {
	// Dev-only: copy hot-reload trigger and ORT WASM files to local vault.
	// In production, users get ORT files auto-downloaded from phonolite.rocks on first launch.
	copyFileSync(".hotreload", `${outdir}/.hotreload`);
	copyFileSync("node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.wasm", `${outdir}/ort-wasm-simd-threaded.wasm`);
	copyFileSync("node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.mjs", `${outdir}/ort-wasm-simd-threaded.mjs`);
	copyFileSync("node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.jsep.mjs", `${outdir}/ort-wasm-simd-threaded.jsep.mjs`);
	copyFileSync("node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.jsep.wasm", `${outdir}/ort-wasm-simd-threaded.jsep.wasm`);
}

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
