import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { copyFileSync, mkdirSync, readFileSync } from 'node:fs';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

// In Electron renderer, process.release.name === 'node', which makes
// @huggingface/transformers set IS_NODE_ENV = true and select onnxruntime-node
// (a native C++ addon that is unavailable) instead of onnxruntime-web (WASM).
// Fix: patch the IS_NODE_ENV expression in transformers.web.js at compile time
// so it is always false, forcing the ort-web (WASM) path.
const patchIsNodeEnvPlugin = {
	name: 'patch-transformers-is-node-env',
	setup(build) {
		build.onLoad({ filter: /transformers\.web\.js$/ }, (args) => {
			const contents = readFileSync(args.path, 'utf8').replace(
				"process?.release?.name === 'node'",
				"false",
			);
			return { contents, loader: 'js' };
		});
	},
};

const prod = (process.argv[2] === "production");

// In dev mode, output directly to the local test vault for hot-reload.
// In production (CI), output to ./dist so the release workflow can pick up artifacts.
const outdir = prod
	? "./dist"
	: "C:\\Users\\matt\\Documents\\programming\\obsidian_test_vault\\.obsidian\\plugins\\phonolite";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	plugins: [patchIsNodeEnvPlugin],
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
		...builtinModules.map(m => `node:${m}`)],
	define: {
		__DEV__: prod ? "false" : "true",
	},
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: `${outdir}/main.js`,
	minify: prod,
});

// Copy static assets needed for both dev and production releases
mkdirSync(outdir, { recursive: true });
copyFileSync("manifest.json", `${outdir}/manifest.json`);
copyFileSync("styles.css", `${outdir}/styles.css`);

if (!prod) {
	// Dev-only: copy hot-reload trigger and ORT WASM files to local vault.
	// In production, users get ORT files auto-downloaded from phonolite.rocks on first launch.
	copyFileSync(".hotreload", `${outdir}/.hotreload`);
	copyFileSync("node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.wasm", `${outdir}/ort-wasm-simd-threaded.wasm`);
	copyFileSync("node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.mjs", `${outdir}/ort-wasm-simd-threaded.mjs`);
	copyFileSync("node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.jsep.mjs", `${outdir}/ort-wasm-simd-threaded.jsep.mjs`);
	copyFileSync("node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.jsep.wasm", `${outdir}/ort-wasm-simd-threaded.jsep.wasm`);
}

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
